spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: moneyminder-expenses
            uri: ${EXPENSES_URL:http://localhost:18081}
            predicates:
              - Path=/api/expenses/**
            filters:
              - StripPrefix=2
          - id: moneyminder-users
            uri: ${USERS_URL:http://localhost:18082}
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=2

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:18082/.well-known/jwks.json}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG