spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: moneyminder-expenses
            uri: ${EXPENSES_URL}
            predicates:
              - Path=/api/expenses/**
            filters:
              - StripPrefix=2
          - id: moneyminder-users
            uri: ${USERS_URL}
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=2

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG